apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # özellik anahtarları bir değerle eşleşmiş şekilde
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # dosya benzeri anahtarlar
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
